workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: Chickie Road
    environment:
      java: 17
      groups:
        - app_store_credentials
        - certificate_credentials
      vars:
        BUNDLE_ID: "com.chickiroad.app"
        XCODE_PROJECT: "iosApp/iosApp.xcodeproj"
        XCODE_SCHEME: "iosApp"
        XCODE_WORKSPACE: "iosApp/iosApp.xcworkspace"
        APP_ID: 6748528162
      xcode: latest
    scripts:
      - name: Set up keychain
        script: |
          keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files $BUNDLE_ID --type IOS_APP_STORE --create
      - name: Add certificates
        script: |
          keychain add-certificates
      - name: Cocoapods installation
        script: |
          cd $CM_BUILD_DIR/iosApp
          pod install
      - name: Set up code signing settings
        script: |
          cd $CM_BUILD_DIR/iosApp
          xcode-project use-profiles
      - name: Build KMP shared framework
        script: |
          export PLATFORM_NAME="iphoneos"
          export ARCHS="arm64"
          export VALID_ARCHS="arm64"
          export SDK_NAME="iphoneos"
          ./gradlew :composeApp:embedAndSignAppleFrameworkForXcode
      - name: Build iOS
        script: |
          cd $CM_BUILD_DIR/iosApp
          xcode-project build-ipa --workspace "$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME"
    artifacts:
      - iosApp/build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration